name: boltz
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2025.7.14=hbd8a1cb_0
  - icu=75.1=he02047a_0
  - ld_impl_linux-64=2.44=h1423503_1
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libgcc=15.1.0=h767d61c_4
  - libgcc-ng=15.1.0=h69a702a_4
  - libgomp=15.1.0=h767d61c_4
  - liblzma=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libsqlite=3.50.3=hee844dc_1
  - libstdcxx=15.1.0=h8f9b012_4
  - libstdcxx-ng=15.1.0=h4852527_4
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.5.1=h7b32b05_0
  - pip=25.1.1=pyh8b19718_0
  - python=3.10.18=hd6af730_0_cpython
  - readline=8.2=h8c095d6_2
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=noxft_hd72426e_102
  - wheel=0.45.1=pyhd8ed1ab_1
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - antlr4-python3-runtime==4.9.3
      - async-timeout==5.0.1
      - attrs==25.3.0
      - biopython==1.84
      - certifi==2025.7.14
      - charset-normalizer==3.4.2
      - chembl-structure-pipeline==1.2.2
      - click==8.1.7
      - cuequivariance==0.5.1
      - cuequivariance-ops-cu12==0.5.1
      - cuequivariance-ops-torch-cu12==0.5.1
      - cuequivariance-torch==0.5.1
      - dm-tree==0.1.8
      - docker-pycreds==0.4.0
      - einops==0.8.0
      - einx==0.3.0
      - fairscale==0.4.13
      - filelock==3.18.0
      - frozendict==2.4.6
      - frozenlist==1.7.0
      - fsspec==2025.7.0
      - gemmi==0.6.5
      - gitdb==4.0.12
      - gitpython==3.1.45
      - hydra-core==1.3.2
      - idna==3.10
      - ihm==2.7
      - jinja2==3.1.6
      - joblib==1.5.1
      - lightning-utilities==0.15.0
      - llvmlite==0.44.0
      - markupsafe==3.0.2
      - mashumaro==3.14
      - modelcif==1.2
      - mpmath==1.3.0
      - msgpack==1.1.1
      - multidict==6.6.3
      - networkx==3.4.2
      - numba==0.61.0
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-ml-py==12.575.51
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - omegaconf==2.3.0
      - opt-einsum==3.4.0
      - packaging==25.0
      - pandas==2.3.1
      - pillow==11.3.0
      - platformdirs==4.3.8
      - propcache==0.3.2
      - protobuf==5.29.5
      - psutil==7.0.0
      - pynvml==12.0.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.1
      - pytorch-lightning==2.5.0
      - pytz==2025.2
      - pyyaml==6.0.2
      - rdkit==2025.3.3
      - requests==2.32.3
      - rootutils==1.0.7
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - sentry-sdk==2.34.1
      - setproctitle==1.3.6
      - six==1.17.0
      - smmap==5.0.2
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - torch==2.7.1
      - torchmetrics==1.8.0
      - tqdm==4.67.1
      - triton==3.3.1
      - types-requests==2.32.4.20250611
      - typing-extensions==4.14.1
      - tzdata==2025.2
      - urllib3==2.5.0
      - wandb==0.18.7
      - yarl==1.20.1
prefix: forks/boltz/boltz
