name: chai-lab
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2024.8.30=hbcca054_0
  - ld_impl_linux-64=2.43=h712a8e2_0
  - libexpat=2.6.3=h5888daf_0
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.1.0=h77fa898_1
  - libgcc-ng=14.1.0=h69a702a_1
  - libgomp=14.1.0=h77fa898_1
  - libnsl=2.0.1=hd590300_0
  - libsqlite=3.46.1=hadc24fc_0
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=h4ab18f5_1
  - ncurses=6.5=he02047a_1
  - openssl=3.3.2=hb9d3cd8_0
  - pip=24.2=pyh8b19718_1
  - python=3.11.10=hc5c86c4_1_cpython
  - readline=8.2=h8228510_1
  - setuptools=74.1.2=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - wheel=0.44.0=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - pip:
      - aiobotocore==2.15.1
      - aiohappyeyeballs==2.4.0
      - aiohttp==3.10.5
      - aioitertools==0.12.0
      - aiosignal==1.3.1
      - antipickle==0.2.0
      - antlr4-python3-runtime==4.9.3
      - asttokens==2.4.1
      - attrs==24.2.0
      - beartype==0.18.5
      - biopython==1.83
      - botocore==1.35.23
      - cachetools==5.5.0
      - certifi==2024.8.30
      - cfgv==3.4.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - comm==0.2.2
      - contourpy==1.3.0
      - cycler==0.12.1
      - db-dtypes==1.3.0
      - debugpy==1.8.5
      - decorator==5.1.1
      - distlib==0.3.8
      - einops==0.8.0
      - executing==2.1.0
      - filelock==3.16.1
      - fonttools==4.54.1
      - frozenlist==1.4.1
      - fsspec==2024.9.0
      - gcsfs==2024.9.0.post1
      - gemmi==0.6.7
      - google-api-core==2.20.0
      - google-auth==2.35.0
      - google-auth-oauthlib==1.2.1
      - google-cloud-bigquery==3.25.0
      - google-cloud-core==2.4.1
      - google-cloud-storage==2.18.2
      - google-crc32c==1.6.0
      - google-resumable-media==2.7.2
      - googleapis-common-protos==1.65.0
      - grpcio==1.66.1
      - grpcio-status==1.66.1
      - huggingface-hub==0.25.1
      - hydra-core==1.3.2
      - identify==2.6.1
      - idna==3.10
      - iniconfig==2.0.0
      - ipykernel==6.29.5
      - ipython==8.27.0
      - jaxtyping==0.2.34
      - jedi==0.19.1
      - jinja2==3.1.4
      - jmespath==1.0.1
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - kiwisolver==1.4.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.9.2
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - modelcif==1.0
      - mpmath==1.3.0
      - msgpack==1.1.0
      - multidict==6.1.0
      - multimethod==1.9
      - mypy==1.11.2
      - mypy-extensions==1.0.0
      - nest-asyncio==1.6.0
      - networkx==3.3
      - nodeenv==1.9.1
      - numba==0.59
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.6.68
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - packaging==24.1
      - pandas==2.2.3
      - pandas-gbq==0.23.2
      - pandas-stubs==2.2.2.240909
      - pandera==0.21.0
      - parso==0.8.4
      - pexpect==4.9.0
      - pillow==10.4.0
      - platformdirs==4.3.6
      - pluggy==1.5.0
      - pre-commit==3.8.0
      - prompt-toolkit==3.0.47
      - proto-plus==1.24.0
      - protobuf==5.28.2
      - psutil==6.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==17.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pydata-google-auth==1.8.2
      - pygments==2.18.0
      - pyparsing==3.1.4
      - pytest==8.3.3
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - pytz==2024.2
      - pyyaml==6.0.2
      - pyzmq==26.2.0
      - rdkit==2023.9.5
      - regex==2024.9.11
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - rich==13.8.1
      - rootutils==1.0.7
      - rsa==4.9
      - ruff==0.6.3
      - s3fs==2024.9.0
      - safetensors==0.4.5
      - shellingham==1.5.4
      - six==1.16.0
      - stack-data==0.6.3
      - sympy==1.13.3
      - tmtools==0.2.0
      - tokenizers==0.19.1
      - torch==2.3.1
      - tornado==6.4.1
      - tqdm==4.66.5
      - traitlets==5.14.3
      - transformers==4.44.2
      - triton==2.3.1
      - typeguard==2.13.3
      - typer==0.12.5
      - types-pytz==2024.2.0.20240913
      - types-pyyaml==6.0.12.20240917
      - types-requests==2.32.0.20240914
      - types-tqdm==4.66.0.20240417
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - urllib3==2.2.3
      - virtualenv==20.26.5
      - wcwidth==0.2.13
      - wrapt==1.16.0
      - yarl==1.12.1
prefix: forks/chai-lab/chai-lab
