name: DiffDock
channels:
  - pyg
  - pytorch
  - senyan.dev
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - antlr-python-runtime=4.9.3=pyhd8ed1ab_1
  - arrow=1.2.3=py39h06a4308_1
  - attrs=22.1.0=py39h06a4308_0
  - backoff=2.2.1=pyhd8ed1ab_0
  - beautifulsoup4=4.12.2=py39h06a4308_0
  - blas=2.116=mkl
  - blas-devel=3.9.0=16_linux64_mkl
  - blessed=1.19.1=pyhe4f9e05_2
  - brotli-python=1.0.9=py39h5a03fae_9
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2023.7.22=hbcca054_0
  - cachecontrol=0.13.1=pyhd8ed1ab_0
  - cachecontrol-with-filecache=0.13.1=pyhd8ed1ab_0
  - certifi=2023.7.22=pyhd8ed1ab_0
  - cffi=1.15.1=py39h5eee18b_3
  - cfgv=3.3.1=py39h06a4308_0
  - charset-normalizer=3.2.0=pyhd8ed1ab_0
  - cleo=2.0.1=py39h06a4308_0
  - click=8.0.4=py39h06a4308_0
  - crashtest=0.4.1=py39h06a4308_0
  - croniter=1.3.7=py39h06a4308_0
  - cryptography=41.0.2=py39h22a60cf_0
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-runtime=11.8.0=0
  - cudatoolkit=11.8.0=h4ba93d1_12
  - cudatoolkit-dev=11.8.0=h1fa729e_6
  - dateutils=0.6.12=py_0
  - dbus=1.13.18=hb2f20db_0
  - deepdiff=6.3.1=pyhd8ed1ab_0
  - distlib=0.3.7=pyhd8ed1ab_0
  - dulwich=0.21.3=py39h5eee18b_0
  - exceptiongroup=1.0.4=py39h06a4308_0
  - expat=2.4.9=h6a678d5_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.12.2=pyhd8ed1ab_0
  - freetype=2.12.1=hca18f0e_1
  - glib=2.69.1=he621ea3_2
  - gmp=6.2.1=h58526e2_0
  - gmpy2=2.1.2=py39h376b7d2_1
  - gnutls=3.6.13=h85f3911_1
  - icu=72.1=hcb278e6_0
  - identify=2.5.5=py39h06a4308_0
  - idna=3.4=pyhd8ed1ab_0
  - importlib-metadata=6.0.0=py39h06a4308_0
  - importlib_metadata=6.0.0=hd3eb1b0_0
  - importlib_resources=5.2.0=pyhd3eb1b0_1
  - iniconfig=1.1.1=pyhd3eb1b0_0
  - inquirer=3.1.3=pyhd8ed1ab_0
  - itsdangerous=2.0.1=pyhd3eb1b0_0
  - jaraco.classes=3.2.1=pyhd3eb1b0_0
  - jeepney=0.7.1=pyhd3eb1b0_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - jpeg=9e=h166bdaf_2
  - jsonschema=4.17.3=py39h06a4308_0
  - keyring=24.2.0=py39hf3d152e_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.15=hfd0df8a_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=4.0.0=h27087fc_0
  - libblas=3.9.0=16_linux64_mkl
  - libcblas=3.9.0=16_linux64_mkl
  - libcublas=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufile=1.7.1.12=0
  - libcurand=10.3.3.129=0
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libdeflate=1.17=h0b41bf4_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.1.0=he5830b7_0
  - libgfortran-ng=13.1.0=h69a702a_0
  - libgfortran5=13.1.0=h15d22d2_0
  - libgomp=13.1.0=he5830b7_0
  - libhwloc=2.9.2=nocuda_h7313eea_1008
  - libiconv=1.17=h166bdaf_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - liblapack=3.9.0=16_linux64_mkl
  - liblapacke=3.9.0=16_linux64_mkl
  - libnpp=11.8.0.86=0
  - libnsl=2.0.0=h7f98852_0
  - libnvjpeg=11.9.0.86=0
  - libpng=1.6.39=h753d276_0
  - libsqlite=3.42.0=h2797004_0
  - libstdcxx-ng=13.1.0=hfd8a6a1_0
  - libtiff=4.5.0=h6adf6a1_2
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.3.1=hd590300_0
  - libxcb=1.13=h7f98852_1004
  - libxml2=2.11.5=h0d562d8_0
  - libzlib=1.2.13=hd590300_5
  - llvm-openmp=15.0.7=h0cdce71_0
  - markdown-it-py=2.2.0=py39h06a4308_1
  - mdurl=0.1.0=py39h06a4308_0
  - mkl=2022.1.0=h84fe81f_915
  - mkl-devel=2022.1.0=ha770c72_916
  - mkl-include=2022.1.0=h84fe81f_915
  - more-itertools=8.12.0=pyhd3eb1b0_0
  - mpc=1.3.1=hfe3b2da_0
  - mpfr=4.2.0=hb012696_0
  - msgpack-python=1.0.3=py39hd09550d_0
  - ncurses=6.4=hcb278e6_0
  - nettle=3.6=he412f7d_0
  - nodeenv=1.7.0=py39h06a4308_0
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.5.0=hfec8fc6_2
  - openssl=3.1.3=hd590300_0
  - ordered-set=4.1.0=py39h06a4308_0
  - orjson=3.8.8=py39h52d8a92_0
  - pcre=8.45=h295c915_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pillow=9.4.0=py39h2320bf1_1
  - pip=23.2.1=pyhd8ed1ab_0
  - pkginfo=1.9.6=py39h06a4308_0
  - platformdirs=3.10.0=py39h06a4308_0
  - pluggy=1.0.0=py39h06a4308_1
  - poetry=1.6.1=linux_pyha804496_0
  - poetry-core=1.7.0=pyhd8ed1ab_0
  - poetry-plugin-export=1.5.0=pyhd8ed1ab_0
  - psutil=5.9.0=py39h5eee18b_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pycparser=2.21=pyhd3eb1b0_0
  - pydantic=1.10.8=py39h5eee18b_0
  - pyg=2.4.0=py39_torch_2.1.0_cu118
  - pygments=2.15.1=py39h06a4308_1
  - pyjwt=2.4.0=py39h06a4308_0
  - pynvml=11.5.0=pyhd8ed1ab_0
  - pyproject_hooks=1.0.0=py39h06a4308_0
  - pyrsistent=0.18.0=py39heee7806_0
  - pysocks=1.7.1=pyha2e5f31_6
  - pytest=7.4.0=py39h06a4308_0
  - python=3.9.17=h0755675_0_cpython
  - python-build=0.10.0=py39h06a4308_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-editor=1.0.4=pyhd3eb1b0_0
  - python-installer=0.7.0=pyhd8ed1ab_0
  - python-multipart=0.0.6=pyhd8ed1ab_0
  - python_abi=3.9=3_cp39
  - pytorch=2.1.0=py3.9_cuda11.8_cudnn8.7.0_0
  - pytorch-cluster=1.6.3=py39_torch_2.1.0_cu118
  - pytorch-cuda=11.8=h7e8668a_5
  - pytorch-mutex=1.0=cuda
  - pytorch-scatter=2.1.2=py39_torch_2.1.0_cu118
  - pytorch-sparse=0.6.18=py39_torch_2.1.0_cu118
  - pytorch-spline-conv=1.2.2=py39_torch_2.1.0_cu118
  - pyyaml=6.0.1=py39hd1e30aa_0
  - rapidfuzz=2.13.7=py39h417a72b_0
  - readchar=4.0.5=pyhd8ed1ab_0
  - readline=8.2=h8228510_1
  - requests=2.31.0=pyhd8ed1ab_0
  - requests-toolbelt=1.0.0=py39h06a4308_0
  - rich=13.3.5=py39h06a4308_0
  - rocm-smi=5.6.0=h59595ed_1
  - secretstorage=3.3.1=py39h06a4308_1
  - setuptools=63.4.1=py39h06a4308_0
  - shellingham=1.5.0=py39h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sniffio=1.2.0=py39h06a4308_1
  - soupsieve=2.4=py39h06a4308_0
  - starlette=0.27.0=pyhd8ed1ab_0
  - starsessions=1.3.0=pyhd8ed1ab_0
  - tbb=2021.10.0=h00ab1b0_0
  - tk=8.6.12=h27826a3_0
  - tomli=2.0.1=py39h06a4308_0
  - tomlkit=0.12.1=pyha770c72_0
  - torchaudio=2.1.0=py39_cu118
  - torchtriton=2.1.0=py39
  - torchvision=0.16.0=py39_cu118
  - traitlets=5.7.1=py39h06a4308_0
  - trove-classifiers=2023.3.9=py39h06a4308_0
  - typing-extensions=4.8.0=hd8ed1ab_0
  - typing_extensions=4.8.0=pyha770c72_0
  - tzdata=2023c=h71feb2d_0
  - ukkonen=1.0.1=py39hdb19cb5_0
  - uvicorn=0.20.0=py39h06a4308_0
  - virtualenv=20.24.3=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - websocket-client=0.58.0=py39h06a4308_4
  - websockets=10.4=py39h5eee18b_1
  - wheel=0.41.1=pyhd8ed1ab_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7b6447c_0
  - zipp=3.11.0=py39h06a4308_0
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.2=hfc55251_7
  - pip:
      - absl-py==1.4.0
      - aiofiles==23.2.1
      - aiohttp==3.8.5
      - aiosignal==1.3.1
      - alembic==1.11.3
      - altair==5.2.0
      - anyio==3.7.1
      - appdirs==1.4.4
      - asttokens==2.2.1
      - async-timeout==4.0.3
      - autopage==0.5.1
      - backcall==0.2.0
      - biopandas==0.5.1.dev0
      - biopython==1.79
      - bioservices==1.11.2
      - boto3==1.28.66
      - botocore==1.31.66
      - cattrs==23.1.2
      - cliff==4.3.0
      - cmaes==0.10.0
      - cmd2==2.4.3
      - colorama==0.4.6
      - colorlog==6.7.0
      - contextlib2==21.6.0
      - contourpy==1.1.0
      - cycler==0.11.0
      - decorator==5.1.1
      - deepspeed==0.9.4
      - git+https://github.com/NVIDIA/dllogger.git@v1.0.0
      - dm-tree==0.1.8
      - docker-pycreds==0.4.0
      - git+https://github.com/e3nn/e3nn.git@a221b2a5498197590cb4fb89fc0af1a5c8acbe17
      - easydev==0.12.1
      - einops==0.6.1
      - executing==1.2.0
      - fair-esm==2.0.0
      - fastapi==0.104.0
      - fastcore==1.5.29
      - ffmpy==0.3.2
      - fonttools==4.42.1
      - frozenlist==1.4.0
      - fsspec==2024.2.0
      - gevent==23.9.1
      - gitdb==4.0.10
      - gitpython==3.1.32
      - gradio==3.50.2
      - gradio-client==0.6.1
      - greenlet==2.0.2
      - grequests==0.7.0
      - h11==0.14.0
      - hjson==3.1.0
      - hydra-colorlog==1.2.0
      - hydra-core==1.3.2
      - hydra-optuna-sweeper==1.2.0
      - httpcore==1.0.4
      - httpx==0.27.0
      - huggingface-hub==0.21.3
      - ipython==8.15.0
      - jedi==0.19.0
      - jmespath==1.0.1
      - joblib==1.2.0
      - kiwisolver==1.4.4
      - lightning-utilities==0.10.1
      - loguru==0.7.2
      - looseversion==1.1.2
      - lovely-numpy==0.2.9
      - lovely-tensors==0.1.15
      - lxml==4.9.3
      - mako==1.2.4
      - markupsafe==2.1.1
      - matplotlib==3.4.3
      - matplotlib-inline==0.1.6
      - ml-collections==0.1.1
      - mmtf-python==1.1.3
      - mpmath==1.2.1
      - multidict==6.0.4
      - multipledispatch==1.0.0
      - natsort==8.4.0
      - networkx==2.8.7
      - ninja==1.11.1
      - numpy==1.23.5
      - omegaconf==2.3.0
      - git+https://github.com/amorehead/openfold.git@fe1275099639bf7e617e09ef24d6af778647dd64
      - opt-einsum==3.3.0
      - opt-einsum-fx==0.1.4
      - optuna==2.10.1
      - packaging==21.3
      - pandas==1.5.0
      - parso==0.8.3
      - pathtools==0.1.2
      - pbr==5.11.1
      - pickleshare==0.7.5
      - plotly==5.17.0
      - prettytable==3.8.0
      - prody==2.4.1
      - prompt-toolkit==3.0.39
      - protobuf==4.24.1
      - pure-eval==0.2.2
      - py-cpuinfo==9.0.0
      - pyaml==21.10.1
      - pybind11==2.11.1
      - pydub==0.25.1
      - pyparsing==3.0.9
      - pyperclip==1.8.2
      - python-dotenv==1.0.0
      - pytz==2022.4
      - rdkit-pypi==2022.3.5
      - requests-cache==1.1.0
      - rich-click==1.6.1
      - rootutils==1.0.7
      - s3transfer==0.7.0
      - scikit-learn==1.1.2
      - scipy==1.12.0
      - seaborn==0.12.2
      - semantic-version==2.10.0
      - sentry-sdk==1.29.2
      - setproctitle==1.3.2
      - smmap==5.0.0
      - spyrmsd==0.5.2
      - sqlalchemy==2.0.20
      - stack-data==0.6.2
      - stevedore==5.1.0
      - suds-community==1.1.2
      - sympy==1.11.1
      - tenacity==8.2.3
      - threadpoolctl==3.1.0
      - toolz==0.12.1
      - tqdm==4.66.1
      - typeguard==4.0.0
      - url-normalize==1.4.3
      - urllib3==1.26.18
      - wandb==0.15.12
      - wget==3.2
      - wrapt==1.15.0
      - xarray==2023.8.0
      - xmltodict==0.13.0
      - yarl==1.9.2
      - zope-event==5.0
      - zope-interface==6.0
prefix: forks/DiffDock/DiffDock
